### ISSUE TITLE
[port_config] Duplicate lanes for two ports in Arista-7050CX3-32S-C32/port_config.ini

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#7371]
#### Description

Lane 128 is assigned to two different ports (`Ethernet124` and `Ethernet132`) in port_config.ini file for `Arista-7050CX3-32S-C32`.

This was last informed in https://github.com/Azure/sonic-buildimage/issues/6569#issuecomment-770139291, and it was decided that this needs to be fixed.

There is no known testcase impact because of this. But, I think this still needs to be corrected.

https://github.com/Azure/sonic-buildimage/blob/01f2b5f250afd0d918abaa61031206cec5f3f359/device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/port_config.ini#L33

https://github.com/Azure/sonic-buildimage/blob/01f2b5f250afd0d918abaa61031206cec5f3f359/device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/port_config.ini#L35
#### Steps to reproduce the issue:
1. Check port_config.ini file content.
2.
3.

#### Describe the results you received:
N/A

#### Describe the results you expected:
N/A

#### Output of `show version`:
N/A

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by lguohan** [comment]
i recall there was a similiar issue and that has been fixed? is this a regression?

**Comment by vaibhavhd** [comment]
> i recall there was a similiar issue and that has been fixed? is this a regression?

This is not a regression. Actually, I don't know if this has caused any testcase failure per se.

However, you are right - this was identified before, and I informed @Staphylo about this.
I found out that the lanes were still not updated, and thus I raised this issue again here now for better visibility, and completion.

**Comment by vaibhavhd** [comment]
May be what you recall is incorrect speeds that were assigned for this HWSKU in the port_Config.ini file. That issue was fixed. But the duplicate lanes remained in the port_Config.ini file.

**Comment by Staphylo** [comment]
@vaibhavhd, sorry, that item slipped from my todo-list. I'll have a look at this today.

**Comment by vaibhavhd** [comment]
Notes from discussion over mail:
The shared lanes between two ports is a valid configuration. In this hwsku there are no restrictions with sharing a physical lane id:
```
Ethernet32/1 is running at 100G which means lane 125 is the active one while 126, 127 and 128 are passive and therefore not used by the SDK.
This is why Ethernet34 works just fine since it can use 128 as an active lane.
````
Closing this issue now.
